Handle error about invalid `__lazy_submodules__`
Summary:
If a module had an invalid `__lazy_submodules__` attribute, the error
was not being handled correctly. This resulted in:

```
SystemError: third-party/python/3.10.cinder/Objects/setobject.c:2303: bad argument to internal function
The above exception was the direct cause of the following exception:
SystemError: _imp._maybe_set_parent_attribute returned a result with an exception set
```

Reviewed By: cxxxs

Differential Revision: D49560412

fbshipit-source-id: ab19a3e27d559c13bb2d15c0fc234daf7402767f