Revert "backport Annotated changes to typing.py from upstream 3.10 to Cinder's typing.py"
Summary:
This reverts D34243192 (https://github.com/facebookincubator/cinder/commit/d2967528330a32924dcb00f2e268ae2d2fc80566). It breaks on codebases that use `typing_extensions.get_type_hints()`
and provide the `include_extras` flag with
`TypeError: get_type_hints() got an unexpected keyword argument 'include_extras'`.

This is because `typing_extensions` defines `get_type_hints` with that flag:
https://github.com/python/typing/blob/master/typing_extensions/src/typing_extensions.py#L1265
But only conditionally if `typing.Annotated` is not defined.

Reviewed By: itamaro

Differential Revision: D34343389

fbshipit-source-id: 65745912ca