Port changes to Makefile.pre.in and configure.ac
Summary:
I squashed all the changes to `configure.ac` and `Makefile.pre.in`
from the range `origin/3.8..cinder/310-phase1-target` into a single commit:

```
git checkout origin/3.8
git checkout cinder/310-phase1-target -- configure.ac Makefile.pre.in
git commit -m "Squash make-related changes"
git rebase --onto origin/cinder/3.10 HEAD^
```

and then rebased that commit onto `origin/cinder/3.10`. This is the result,
after resolving the conflicts and fixing a few things to keep build/tests
working (search for `TODO(T125621044)`).

I left out the changes from a couple upstream commits related to
`-fno-semantic-interposition` during the rebase; see the attached task for
details/follow-up.

Also:
- Add a bunch of `.PHONY` targets at the end of `Makefile.pre.in` that were
  missing from `cinder/310-phase1-target; most people don't know we should be
  adding test targets there.
- Fix some warnings in `_testcapimodule.c` and `_asynciomodule.c` that are
  errors with this diff.

The following diffs are represented in this port:
D22964960: Add Makefile target for the cinder subset of the unit test suite
D22964961: Enable bytecode tracing with DTRACE
D22983648: instalab and JIT commits
D23008622: Ports lots of jit diffs
D23012645: 36 commits in ThirdParty/asmjit/, Jit/, RuntimeTests/, Python/ceval.c, Makefile.pre.in by mpage@fb.com, tiansi@fb.com
D23057897: More JIT commits
D23275587: [3.8] Port 14 more JIT commits
D23330390: [3.8] Port 21 commits
D23361836: [3.8] Port 3 commits
D23380335: [3.8] Port 9 commits
D23384109: [3.8] Port 9 commits (notably enabling -Werror for .cpp files)
D23391094: [3.8] Port 7 JIT commits
D23391465: [3.8] Port 6 commits
D23405150: [3.8] Port 8 commits (notably enabling dict watchers)
D23405685: [3.8] Port 7 commits
D23407043: [3.8] Port 2 commits
D23412517: [3.8] Port 8 commits (notably FOR_ITER support)
D23413599: [3.8] Port 5 commits
D23430014: [3.8] Port 29 commits
D23442978: [3.8] Port 10 commits
D23443256: [3.8] Port a couple of static python changes
D23461176: [3.8] Port 7 commits (mix of static python and JIT)
D23464584: [3.8] Port 8 commits (mostly static python)
D23484732: [3.8] Add `-Werror` for .c files
D23465816: Bring shadow code over
D23661793: [3.8] Port: New refcount insertion pass
D23714463: [3.8] Port 3 commits related to LIR from cinder 3.7
D23717501: [3.8] Port: [py-static] Move array module to Python core
D23639621: [3.8] Enable ASAN tests
D23855348: [3.8] Port 3 commits from cinder 3.7
D23950881: [3.8] append _static suffix to static lib name
D23997975: [cinder][pyre] Port union changes from cpython into cinder/3.8.
D24146887: Disable some tests on ASAN
D24434347: Port 3.8: JIT: first milestone of code generator for the new register allocator
D24805657: [3.8] Port: JIT: Sort basic blocks
D25081466: [3.8] Port: JIT: second milestone of the new JIT backend
D25312267: [3.8 Port][build] allow overriding PLATFORM_TRIPLET
D25411291: Port code_gen to genasm
D26132445: [cinder3.8] Skip instrumented PGO build for clang --enable-optimizations
D26143132: Add support for annotated disassembly and `-X jit-dump-lir` with new backend
D26069393: Start reimplement strict module in cinder
D26268157: Add sandcastle command to run strict module test
D26288852: Add StrictModules directories to configure.ac
D26191554: [strict modules]Add python interface to cinder implementation
D26284897: Refactor `Ref`
D26536478: Refactor JIT list implementation
D26262185: [strict modules] Move over scope handling
D26357392: [strict modules]Add ability to compare with python values
D26613944: JIT: Remove old backend
D26505866: [strict modules]Port over error sink
D26898758: Remove Jit/compiler_interface.*
D26835472: Support RR in jit_test_runner
D26854339: [jit] Refactor bytecode iteration
D27004604: [strict modules]Port over basic object model
D27210670: [strict modules] Port over callables
D27451083: Generate machine-readable recording metadata file
D27514711: Fix some paths in STRICTM_OBJS
D27241504: [strict modules] port over list, set, tuple
D27351666 (https://github.com/facebookincubator/cinder/commit/51f8e83ab467e4a3e6b9cb643dc8afc7f437a5ef): [jit] Import parallel-hashmap library and provide shim for using it
D27983693 (https://github.com/facebookincubator/cinder/commit/88ddbfa556956fa7ccf17f168eaa953c02f376a8): [OSS] Add OSS CI
D28022437 (https://github.com/facebookincubator/cinder/commit/89374de5fab65c740cabc8c5f6492e0f412d57be): [OSS] Make "configure + make" with no args work
D27409691 (https://github.com/facebookincubator/cinder/commit/5e463140853b88d61f7c44f1174ba6400a185e67): [strict modules] Iterator support
D27444217 (https://github.com/facebookincubator/cinder/commit/a95ab42bddb7f90330acf65248403eaf11f0cfe1): [strict modules] Switch to Ref to manage PyObjects
D27479471 (https://github.com/facebookincubator/cinder/commit/f86f24be00bfdaefb8c88703eaeb03f0fa3fe64b): [strict modules]Port over dict objects
D27522732 (https://github.com/facebookincubator/cinder/commit/bcda75658a009604148932f674e3811196853837): [strict modules]Port over function object
D27727868 (https://github.com/facebookincubator/cinder/commit/36bcb6f3ee4858f2d6cdf1ab0a01471edcd292dc): [JIT] Multi-threaded compile
D28305978 (https://github.com/facebookincubator/cinder/commit/c9736e7ca59a22e5cf3cda9f55362a06e0464e71): Fix undefined reference to shm_open
D28012165 (https://github.com/facebookincubator/cinder/commit/d3ae2a4dcdc57f3a48e141df901a52e591acb5a9): Refactor `CodeGen`
D28339350 (https://github.com/facebookincubator/cinder/commit/7a1d0ad6788587eb00380833489d240729ac8ba5): Add missing linker flag
D28346650 (https://github.com/facebookincubator/cinder/commit/8ac151d62a7117db7510a429a3ccaf45167550b3): Add shadow frame mode
D28728674 (https://github.com/facebookincubator/cinder/commit/afb637523d5f0fdd358a047ebe02a0cafa6f3403): Disable multi-threaded-compile test for now
D28881526 (https://github.com/facebookincubator/cinder/commit/601512fbcb7f1e003e13dbac10bfe973786879fc): Remove dead refernces to -X shadowcode
D29168120 (https://github.com/facebookincubator/cinder/commit/5f95bb2a7819888c822601ac0f14ed37afdb25c9): Remove `cinderlab` and `instalab` from makefile
D27684718 (https://github.com/facebookincubator/cinder/commit/5f8f6b412231ab93edabdd4c8c667ae3f01aaee5): [strict modules] Implement simple visits and unlock tests
D27902063 (https://github.com/facebookincubator/cinder/commit/f5735f849a960eeec6037578cdb66cc0cc524702): [strict modules] Port over super()
D27949809 (https://github.com/facebookincubator/cinder/commit/6d25341f417d5f6d8e06c460823bcbd1450368c0): [strict modules] properties and prepare handling
D27979850 (https://github.com/facebookincubator/cinder/commit/5374128744d1bbdeddf5106f8e930e3e805ce751): [strict modules]Port over more builtins
D28098312 (https://github.com/facebookincubator/cinder/commit/fca9de8d1bab3ba9d959df00ea75f92ada9d441a): [strict modules] Port over code object
D28159651 (https://github.com/facebookincubator/cinder/commit/8a8eb0dcf5acb1247feda24b2f7c10c2ac211b02): [strict modules] Port over union type
D29214635 (https://github.com/facebookincubator/cinder/commit/51a49376d7f02838be1b55a044eda3a4f22fb620): [cinder][lir] Resolve symbols (function names, string literals) in LIR parser
D29241052 (https://github.com/facebookincubator/cinder/commit/d0c68db8ed0d4c697bbc1f4ebafecd958e12558a): Add Simplify pass
D28511888 (https://github.com/facebookincubator/cinder/commit/0a9a39a9349e577ca028895c7277e805a579d639): [strict modules] introduce sequence_map
D29871473 (https://github.com/facebookincubator/cinder/commit/53cc3294ae69a80f44286e9b3c5817be199156ca): Fix broken build
D28395668 (https://github.com/facebookincubator/cinder/commit/24e22ed97d05690535a149e888f08882c5a7a82d): [strict modules] Add stub support
D29139665 (https://github.com/facebookincubator/cinder/commit/770195452cf43aaaefaa8985d7737f574b7036e1): [strict modules] Lazy import from statement
D29567888 (https://github.com/facebookincubator/cinder/commit/4f1b313cb50b021f13c9f4bd3a43c026f36e931a): [strict modules] Move over the "strict module" module builtins
D29617298 (https://github.com/facebookincubator/cinder/commit/1139869062bebf777509d785a8c3fe402c710d59): [strict modules] Implement a preprocessor
D30027914 (https://github.com/facebookincubator/cinder/commit/9f90fcc8361b5d9f923ccca025c78cf287b2d9c0): [cinder][lir] Use map of C helper LIR text instead of text files
D30155352 (https://github.com/facebookincubator/cinder/commit/ea4636c878dea6f7dedb2afbf988c3d1cb77fe89): [strict modules] add __strict__ module to makefile
D30168811 (https://github.com/facebookincubator/cinder/commit/72131175cfc7e76c19f99cf6fa417d1fe47ff895): [strict modules] move loader
D30524470 (https://github.com/facebookincubator/cinder/commit/bfe07f566810b0b2af4679dc21333ce190ff5af1): [cinder][lir] Set up kCHelperMappingAuto for automatically generated LIR's
D30824671 (https://github.com/facebookincubator/cinder/commit/196fa17f8b6ac8d3c1bdc89523fda5f5497ea9c1): CIPP: Add PyConstObject Type
D31177282 (https://github.com/facebookincubator/cinder/commit/72b2c53105bc2e15a635646c783df24888b44c32): Add missing shadow frame header to Makefile
D31067400 (https://github.com/facebookincubator/cinder/commit/0370e64ee31d351fa67a2306440a211643d0b2f9): Rename `TypeProfiler` to `FixedTypeProfiler`, add new `TypeProfiler`
D31627164 (https://github.com/facebookincubator/cinder/commit/4d0e04a61d5a7564c19356973cac20f7545ccb11): Fix refcounting bug in strictmodule_exec()
D31491152 (https://github.com/facebookincubator/cinder/commit/eacde874d20d54b9efd9a168f359a457fa957a38): Add infrastructure for code invalidation
D31065920 (https://github.com/facebookincubator/cinder/commit/cf99db9f18e2fdee799643de73d275da592738c1): Add interpreter type profiling
D31750773 (https://github.com/facebookincubator/cinder/commit/89ec39a885957bf6c1eaed5bf4439b376399b50c): Replace (most) macros in type.h with a Python script
D32302084 (https://github.com/facebookincubator/cinder/commit/ed598d6549e92903846856e1b8460f6e8ae73d84): [jit] begin consolidating classloader lookups in preload pass
D31836766 (https://github.com/facebookincubator/cinder/commit/b1d69179f4643582c466a227a6dec13015348bbb): Add a way for HIR instructions to define their operand types
D32603054 (https://github.com/facebookincubator/cinder/commit/aae083490486d1b4fe4c2cfc98a5c432e1320d46): [cinder]Add option to use python written compiler
D32896422 (https://github.com/facebookincubator/cinder/commit/0069b4e32ff29dc8ae4f119a563773edb71249c9): [cinder][lir] add a dead-code elimination pass to the LIR
D33469569 (https://github.com/facebookincubator/cinder/commit/03bcbc185c0cc39b6d3c211d80529bec204eaae9): JIT: Fix a case where CondBranch rewrite will fail
D33463323 (https://github.com/facebookincubator/cinder/commit/d6c3c7b93c4a8462dee9135f3b84ae41ee6a560d): Fix memory leak in posix module
D33549283 (https://github.com/facebookincubator/cinder/commit/488258c87721fa58ff415a6f9e865acd2969548b): [strict] move default stubs into Lib/compiler/strict
D33535425 (https://github.com/facebookincubator/cinder/commit/c7d6540f42049ebc4dd0186694f63d941edb24c8): Add LiveTypeMap
D32571983 (https://github.com/facebookincubator/cinder/commit/52ad55571b8495a412865d986a73df2b628203fe): Add ability to write profile data to disk, emit guards in HIRBuilder
D33594435 (https://github.com/facebookincubator/cinder/commit/8bb54d73352882e0372d6802cfad59b7cbe3e323): Update `f_lasti` when materializing frames
D33993494 (https://github.com/facebookincubator/cinder/commit/a6c2824fe98860bb4e2a8a8b818ccfabce9d1296): Tests for cmdline flags in pyjit.cpp
D33273017 (https://github.com/facebookincubator/cinder/commit/df0dfbb40379d5e552fb2fe48ec0a09921d1c123): [readonly]Fix initial version of readonly checker
D33860823 (https://github.com/facebookincubator/cinder/commit/06706ee33e6c9e92540ea36c98617deef5e9ab94): Introduce __function_credential__
D33834913 (https://github.com/facebookincubator/cinder/commit/778bcbecce46564baa1725583f2abb1e17870eff): [JIT] Basic support for putting code on huge pages
D34198795 (https://github.com/facebookincubator/cinder/commit/0f25c4fef3cd3822a0a0e2b6622cb4d01dbb72a3): Systematise JIT flag parsing
D34548342 (https://github.com/facebookincubator/cinder/commit/428669a9a925287f192ab361226e5a8ca3fb74d9): Add nlohmann's JSON 3.10.5
D33752316 (https://github.com/facebookincubator/cinder/commit/f6a90d67eb3fa0e5c2e01cf1e9a345ccab1ae333): Add test runners that enable the inliner in CI
D34625518 (https://github.com/facebookincubator/cinder/commit/7097916ddf3bef6319aed06d956574dc48cd499b): [cinder][lir] move postgen.{cpp, h} to live under lir/ instead of codegen
D34625653 (https://github.com/facebookincubator/cinder/commit/c44aecce99cf22627219051c42c63b83931a022e): [cinder][lir] move postalloc.{cpp, h} to live under lir/ instead of codegen
D34626168 (https://github.com/facebookincubator/cinder/commit/8ef43e1220a8e8f13655ec65f81119dfe0df8e91): [cinder][lir] move rewrite.{cpp, h} to live under lir/ instead of codegen/
D34626363 (https://github.com/facebookincubator/cinder/commit/fc97baaa1ba9f8412b80e39187d0538bdbfd3480): [cinder][lir] move regalloc.{cpp, h} from codegen to lir
D34642767 (https://github.com/facebookincubator/cinder/commit/3339eeb876e62059c74dfdfb69438ad1dd774255): [cinder][jit] move inliner.{cpp, h} to live under lir/ instead of codegen/
D34675352 (https://github.com/facebookincubator/cinder/commit/69122a536bf60f9ce86adb9b47b0fc8fd9cc45c1): New -X jit-time timing tool
D34873159 (https://github.com/facebookincubator/cinder/commit/32b0062fd097e4d0292a4a8d3dbde3a2dcda1139): [cinder][lir] introduce a verification pass to the LIR
D34895163 (https://github.com/facebookincubator/cinder/commit/a1da08253fdb5961ca74d7aa3d108a8fac38dc24): [cinder] support CondBranch to blocks where both successors are non-adjacent
D34900318 (https://github.com/facebookincubator/cinder/commit/4337e631aab72fb62287116734f1dc18d13361a6): [cinder][lir] introduce code section hints to LIR basic blocks and add parsing support
D34657350 (https://github.com/facebookincubator/cinder/commit/8345c4e294b1a7782107bf3bca6650a154f1c5dd): [immutable]Unified format for immutable errors
D35231227 (https://github.com/facebookincubator/cinder/commit/c87ae4a55523ab8bc2dd926e94467e939e2d59f8): [immutable] Add immutable_globals
D35063602 (https://github.com/facebookincubator/cinder/commit/73a99f659c68e20f551c83b8b1c64bcff1489b28): [cinder][readonly] Add support for binary opcodes
D35015003 (https://github.com/facebookincubator/cinder/commit/f3973da07771b95b4bff45352b1a54a433d051c3): [cinder] introduce a multiple section code allocator
D35731988 (https://github.com/facebookincubator/cinder/commit/d174a10e89067c59ee80176ab9f5f84aaecb8ecc): Factor testcinder_jit variants into function call
D35764679 (https://github.com/facebookincubator/cinder/commit/58a5a29707d213ca7957dce9d1c5d12c7d6f6cb2): Add Python tests that use profile data
D34980669 (https://github.com/facebookincubator/cinder/commit/cba54771693a26c904326e8eb24abd33d8415646): [cinder] Upgrade to fmt 8.1.1
D35657165 (https://github.com/facebookincubator/cinder/commit/e7561f564dbf59ebacffec5654be4b37ca8f7ad8): Track code locations for inlined functions
D36238598 (https://github.com/facebookincubator/cinder/commit/5c04dc52227aae03990377f4186f6c7d63b7da25): [cinder] Add support for PGO builds with clang
D36993444 (https://github.com/facebookincubator/cinder/commit/cd852cdba067c15095ca5c88612be6edaa39f08a): Allocate runtime JIT caches together
D35984663 (https://github.com/facebookincubator/cinder/commit/09520fce394f524c8cdda9d830ab211b9958231f): [cinder] Bump to C++20
D36873853 (https://github.com/facebookincubator/cinder/commit/8e85ae27c9fcb2aec66216c54ad8e7c56dd43b58): Add cindervm as C extension module
D37324852 (https://github.com/facebookincubator/cinder/commit/2f1f01ca73a9d3e795622d7ffefa5dd56b312cdd): Add fuzzer/verifier tests to CI and linter

Reviewed By: jbower-fb

Differential Revision: D37721831

fbshipit-source-id: b41eb92e87d44225e30ef5a6800953de2c686f32