Fix return type for bad calls with primitive returns
Summary:
Currently, the added test case causes the runtime to crash:
```
Fatal Python error: a function returned a result with an error set
Python runtime state: initialized
TypeError: fn() missing 2 required positional arguments: 'x' and 'y'

The above exception was the direct cause of the following exception:

SystemError: <function fn at 0x7fadb3eddc30> returned a result with an error set

```

This is because `JITRT_CallWithIncorrectArgcount` does not account for
primitive return values.

Updated it to respect those.

Reviewed By: swtaarrs

Differential Revision: D29916919

fbshipit-source-id: 7a80b531c2