deltablue: declare dst before while loop (#110)
Summary:
Fix a type error

I was running commit fa0ed519af6c131ec141f7bd14ab12a4aa7afc1b

`python -m compiler --static deltablue...py`  gave this error:

```
....
  File "/vol/Lib/compiler/static/visitor.py", line 44, in visit
    return super().visit(node, *args)
  File "/vol/Lib/compiler/visitor.py", line 70, in visit
    return meth(node, *args)
  File "/vol/Lib/compiler/static/type_binder.py", line 1592, in visitName
    raise TypedSyntaxError(f"Name `{node.id}` is not defined.")
  File "main.py", line 645
    if dst.value != 1170:
      ^
compiler.errors.TypedSyntaxError: Name `dst` is not defined.
```

All better with this fix.

Pull Request resolved: https://github.com/facebookincubator/cinder/pull/110

Reviewed By: carljm

Differential Revision: D45664724

Pulled By: swtaarrs

fbshipit-source-id: fa27ab71e69d7e4e89988baa077e6dd49f794f47