Make `fdb/rr` work with the jit test runner
Summary:
Python 3.10 started unconditionally setting `PYTHONREGRTEST_UNICODE_GUARD`
to a unicode value when setting up regression tests:

```
Added a permanent Unicode-valued environment variable to regression tests to
ensure they handle this use case in the future. If your test environment
breaks because of that, report a bug to us, and temporarily set
PYTHONREGRTEST_UNICODE_GUARD=0 in your test environment.
```

Either `fdb` or `rr` is failing to handle this and is throwing errors
like:

```
./python  -X jit  ./Tools/scripts/jit_test_runner.py dispatcher  --use-rr -- -w --ignorefile ./Tools/scripts/cinder_jit_ignore_tests.txt
Using scheduling log file /tmp/jit_test_runner_logs/tmpo6mrnz53
Spawning 16 workers
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "test_1781345_tmp\xE7w\xF0"', library/std/src/env.rs:171:83
```

The value in the error message, `test_1781345_tmp\xE7w\xF0`, is the
value of the environment variable `PYTHONREGRTEST_UNICODE_GUARD`.

This does what the Python docs suggest and sets the variable to `0`
before spawning `fdb/rr`.

Reviewed By: tekknolagi

Differential Revision: D38801212

fbshipit-source-id: 7c84b7b16f4e0156b359a895714f3ece7378eff2